import streamlit as st
import pandas as pd
import numpy as np
from datetime import datetime
import io

st.set_page_config(page_title="PDF Report Generator", page_icon="📋", layout="wide")

st.title("📋 Land Intelligence Report Generator")
st.write("Generate a comprehensive AI-powered land analysis report in PDF format.")

def calculate_investment_score(inputs):
    location = min(100, (10 - inputs['distance_city']) * 8 + inputs['road_connectivity'] * 5 + inputs['water_availability'] * 4)
    infrastructure = min(100, inputs['electricity'] * 10 + inputs['water_availability'] * 8 + inputs['internet'] * 6)
    market = min(100, inputs['price_appreciation'] * 10 + inputs['market_demand'] * 8 + inputs['rental_yield'] * 7)
    legal = min(100, inputs['clear_title'] * 25 + inputs['no_disputes'] * 25 + inputs['registered'] * 20 + inputs['govt_approved'] * 15)
    risk = min(100, (10 - inputs['flood_risk']) * 8 + (10 - inputs['pollution']) * 6 + inputs['soil_stability'] * 6)
    overall = location * 0.30 + infrastructure * 0.20 + market * 0.25 + legal * 0.15 + risk * 0.10
    return {
        'Location': round(location, 1),
        'Infrastructure': round(infrastructure, 1),
        'Market': round(market, 1),
        'Legal': round(legal, 1),
        'Risk': round(risk, 1),
        'Overall': round(overall, 1)
    }

def predict_price(area, distance, road, water, electricity, zone, land_type):
    base = area * 500
    city_factor = (100 - distance) * 1000
    infra_factor = (road + water + electricity) * 5000
    zone_mult = {'Urban': 3.0, 'Semi-Urban': 1.8, 'Rural': 1.0}[zone]
    type_mult = {'Commercial': 4.0, 'Industrial': 3.0, 'Residential': 2.0, 'Agricultural': 1.0}[land_type]
    return int((base + city_factor + infra_factor) * zone_mult * type_mult)

def get_fraud_risk(price_deviation, speed, prev_owners, doc_completeness):
    risk = 0
    if price_deviation < -40: risk += 40
    elif price_deviation < -20: risk += 20
    if speed < 7: risk += 30
    elif speed < 15: risk += 15
    if prev_owners > 7: risk += 20
    elif prev_owners > 4: risk += 10
    if doc_completeness < 50: risk += 20
    elif doc_completeness < 70: risk += 10
    return min(100, risk)

def generate_pdf_report(data):
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
    from reportlab.lib.enums import TA_CENTER, TA_LEFT

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                           rightMargin=0.75*inch, leftMargin=0.75*inch,
                           topMargin=0.75*inch, bottomMargin=0.75*inch)

    styles = getSampleStyleSheet()
    story = []

    # Title style
    title_style = ParagraphStyle('Title', parent=styles['Title'],
                                fontSize=22, textColor=colors.HexColor('#1a5276'),
                                spaceAfter=6, alignment=TA_CENTER)
    subtitle_style = ParagraphStyle('Subtitle', parent=styles['Normal'],
                                   fontSize=11, textColor=colors.HexColor('#2e86c1'),
                                   spaceAfter=4, alignment=TA_CENTER)
    heading_style = ParagraphStyle('Heading', parent=styles['Heading2'],
                                  fontSize=13, textColor=colors.HexColor('#1a5276'),
                                  spaceBefore=12, spaceAfter=6)
    normal_style = ParagraphStyle('Normal', parent=styles['Normal'],
                                 fontSize=10, spaceAfter=4)

    # Header
    story.append(Paragraph("🏡 BhumiAI", title_style))
    story.append(Paragraph("AI Land Intelligence & Legal Verification Platform", subtitle_style))
    story.append(Paragraph("Comprehensive Land Analysis Report", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor('#1a5276')))
    story.append(Spacer(1, 0.2*inch))

    # Report info
    report_data = [
        ['Report ID', f'BhumiAI-{datetime.now().strftime("%Y%m%d%H%M%S")}',
         'Date', datetime.now().strftime("%d %B %Y")],
        ['Property Location', data['location'], 'State', data['state']],
        ['Land Type', data['land_type'], 'Zone', data['zone']],
        ['Area', f"{data['area']:,} sq ft", 'Generated By', 'BhumiAI Platform'],
    ]
    t = Table(report_data, colWidths=[1.5*inch, 2.2*inch, 1.2*inch, 2.2*inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (0,-1), colors.HexColor('#d6eaf8')),
        ('BACKGROUND', (2,0), (2,-1), colors.HexColor('#d6eaf8')),
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
        ('PADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.2*inch))

    # Price Prediction
    story.append(Paragraph("1. Land Price Prediction", heading_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#aed6f1')))
    story.append(Spacer(1, 0.1*inch))

    price = data['predicted_price']
    price_data = [
        ['Predicted Market Value', f"₹ {price:,}",
         'Price per sq ft', f"₹ {price//data['area']:,}"],
        ['Value in Lakhs', f"₹ {price/100000:.2f}L",
         'Value in Crores', f"₹ {price/10000000:.3f} Cr"],
        ['ML Model Used', 'Random Forest', 'Training Data', '1000 Indian Land Records'],
    ]
    t2 = Table(price_data, colWidths=[1.8*inch, 2*inch, 1.8*inch, 2*inch])
    t2.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (0,-1), colors.HexColor('#d5f5e3')),
        ('BACKGROUND', (2,0), (2,-1), colors.HexColor('#d5f5e3')),
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
        ('PADDING', (0,0), (-1,-1), 6),
        ('FONTNAME', (1,0), (1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (1,0), (1,0), 11),
        ('TEXTCOLOR', (1,0), (1,0), colors.HexColor('#1a5276')),
    ]))
    story.append(t2)
    story.append(Spacer(1, 0.15*inch))

    # Investment Score
    story.append(Paragraph("2. Investment Score Analysis", heading_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#aed6f1')))
    story.append(Spacer(1, 0.1*inch))

    scores = data['investment_scores']
    overall = scores['Overall']
    if overall >= 80: recommendation = "EXCELLENT INVESTMENT — Strong Buy Recommended"
    elif overall >= 65: recommendation = "GOOD INVESTMENT — Recommended with Due Diligence"
    elif overall >= 50: recommendation = "MODERATE INVESTMENT — Proceed with Caution"
    else: recommendation = "POOR INVESTMENT — Not Recommended"

    story.append(Paragraph(f"<b>Overall Score: {overall}/100 — {recommendation}</b>", normal_style))
    story.append(Spacer(1, 0.1*inch))

    score_data = [['Category', 'Score', 'Rating']]
    for cat, score in scores.items():
        if cat != 'Overall':
            rating = "Excellent" if score >= 80 else "Good" if score >= 60 else "Average" if score >= 40 else "Poor"
            score_data.append([cat, f"{score}/100", rating])

    t3 = Table(score_data, colWidths=[2.5*inch, 1.5*inch, 3.5*inch])
    t3.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1a5276')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTNAME', (0,1), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
        ('PADDING', (0,0), (-1,-1), 6),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor('#ebf5fb')]),
    ]))
    story.append(t3)
    story.append(Spacer(1, 0.15*inch))

    # Fraud Risk
    story.append(Paragraph("3. Fraud Risk Assessment", heading_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#aed6f1')))
    story.append(Spacer(1, 0.1*inch))

    fraud_risk = data['fraud_risk']
    if fraud_risk < 20: fraud_level = "LOW RISK — Transaction appears legitimate"
    elif fraud_risk < 50: fraud_level = "MEDIUM RISK — Proceed with caution"
    else: fraud_level = "HIGH RISK — Suspicious transaction detected"

    fraud_data = [
        ['Fraud Risk Score', f"{fraud_risk}/100", 'Risk Level', fraud_level],
        ['Detection Method', 'Isolation Forest', 'Algorithm', 'Anomaly Detection'],
    ]
    t4 = Table(fraud_data, colWidths=[1.5*inch, 1*inch, 1.5*inch, 3.5*inch])
    t4.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (0,-1), colors.HexColor('#fdecea')),
        ('BACKGROUND', (2,0), (2,-1), colors.HexColor('#fdecea')),
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 9),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
        ('PADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(t4)
    story.append(Spacer(1, 0.15*inch))

    # AI Recommendations
    story.append(Paragraph("4. AI Recommendations", heading_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#aed6f1')))
    story.append(Spacer(1, 0.1*inch))

    recommendations = []
    if overall >= 70:
        recommendations.append("✓ Strong investment opportunity — consider proceeding with purchase")
    if fraud_risk < 20:
        recommendations.append("✓ Transaction risk is low — documents appear legitimate")
    if fraud_risk > 50:
        recommendations.append("⚠ High fraud risk detected — verify all documents carefully")
    if scores['Legal'] < 60:
        recommendations.append("⚠ Legal score is low — consult a property lawyer before purchase")
    if scores['Location'] > 75:
        recommendations.append("✓ Excellent location score — high appreciation potential")
    recommendations.append("✓ Always verify documents at Sub-Registrar office before finalizing")
    recommendations.append("✓ Check Bhulekh portal for Odisha land records verification")

    for rec in recommendations:
        story.append(Paragraph(f"• {rec}", normal_style))

    story.append(Spacer(1, 0.2*inch))

    # Footer
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#1a5276')))
    footer_style = ParagraphStyle('Footer', parent=styles['Normal'],
                                 fontSize=8, textColor=colors.grey, alignment=TA_CENTER)
    story.append(Paragraph(
        f"Generated by BhumiAI — AI Land Intelligence Platform | {datetime.now().strftime('%d %B %Y %H:%M')} | "
        "For informational purposes only. Consult legal experts for final decisions.",
        footer_style
    ))

    doc.build(story)
    buffer.seek(0)
    return buffer

# UI
st.markdown("---")
st.subheader("📝 Enter Land Details")

col1, col2, col3 = st.columns(3)

with col1:
    st.write("**📍 Property Info**")
    location = st.text_input("Property Location", value="Patia, Bhubaneswar")
    state = st.selectbox("State", ['Odisha', 'Maharashtra', 'Karnataka', 'Delhi', 'Gujarat'])
    area = st.number_input("Area (sq ft)", min_value=100, max_value=100000, value=2400)
    land_type = st.selectbox("Land Type", ['Residential', 'Commercial', 'Agricultural', 'Industrial'])
    zone = st.selectbox("Zone", ['Urban', 'Semi-Urban', 'Rural'])

with col2:
    st.write("**🏗️ Infrastructure**")
    distance_city = st.slider("Distance from City (1=Far,10=Close)", 1, 10, 7)
    road_connectivity = st.slider("Road Connectivity (1-10)", 1, 10, 8)
    water_availability = st.slider("Water Availability (1-10)", 1, 10, 8)
    electricity = st.slider("Electricity Supply (1-10)", 1, 10, 9)
    internet = st.slider("Internet Connectivity (1-10)", 1, 10, 7)

with col3:
    st.write("**⚖️ Legal & Market**")
    clear_title = st.checkbox("Clear Title", value=True)
    no_disputes = st.checkbox("No Legal Disputes", value=True)
    registered = st.checkbox("Registered Documents", value=True)
    govt_approved = st.checkbox("Govt Approved", value=True)
    price_appreciation = st.slider("Price Appreciation (1-10)", 1, 10, 7)
    market_demand = st.slider("Market Demand (1-10)", 1, 10, 7)
    rental_yield = st.slider("Rental Yield (1-10)", 1, 10, 6)
    flood_risk = st.slider("Flood Risk (1=Low)", 1, 10, 2)
    pollution = st.slider("Pollution (1=Low)", 1, 10, 2)
    soil_stability = st.slider("Soil Stability (1-10)", 1, 10, 8)

if st.button("📋 Generate PDF Report", type="primary"):
    with st.spinner("Generating your professional report..."):

        predicted_price = predict_price(area, distance_city, road_connectivity,
                                       water_availability, electricity, zone, land_type)

        inv_inputs = {
            'distance_city': distance_city, 'road_connectivity': road_connectivity,
            'water_availability': water_availability, 'electricity': electricity,
            'internet': internet, 'price_appreciation': price_appreciation,
            'market_demand': market_demand, 'rental_yield': rental_yield,
            'clear_title': int(clear_title), 'no_disputes': int(no_disputes),
            'registered': int(registered), 'govt_approved': int(govt_approved),
            'flood_risk': flood_risk, 'pollution': pollution, 'soil_stability': soil_stability
        }

        investment_scores = calculate_investment_score(inv_inputs)
        fraud_risk = get_fraud_risk(-10, 45, 2, 85)

        data = {
            'location': location, 'state': state, 'area': area,
            'land_type': land_type, 'zone': zone,
            'predicted_price': predicted_price,
            'investment_scores': investment_scores,
            'fraud_risk': fraud_risk
        }

        pdf_buffer = generate_pdf_report(data)

        st.success("✅ Report Generated Successfully!")

        col1, col2, col3 = st.columns(3)
        with col1:
            st.metric("Predicted Price", f"₹{predicted_price:,}")
        with col2:
            st.metric("Investment Score", f"{investment_scores['Overall']}/100")
        with col3:
            st.metric("Fraud Risk", f"{fraud_risk}/100")

        st.download_button(
            label="📥 Download PDF Report",
            data=pdf_buffer,
            file_name=f"BhumiAI_Report_{location.replace(' ','_')}_{datetime.now().strftime('%Y%m%d')}.pdf",
            mime="application/pdf"
        )